parameters:
#    ace_generic.example.class: Ace\GenericBundle\Example

services:
#    ace_generic.example:
#        class: %ace_generic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
