imports:
    - { resource: parameters.dist.ini}
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:      { fallback: en }
    #translator:     ~
    secret:          %my.secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: en 
        auto_start:     true
        lifetime:       2592000
        
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        site_name: "codebender"
        email_addr: %email.addr%
        compiler: %compiler%
        sender: %sender%
        library: %library%
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_pass%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
   transport:   gmail
   username:    %email.user%
   password:    %email.pass%
   # port:    465
   encryption:  ssl
   auth_mode:  login
    #spool:
        #type:                 file
        #path:                 %kernel.cache_dir%/swiftmailer/spool
    #sender_address:       ~
    #antiflood:
        #threshold:            99
        #sleep:                0
    #delivery_address:     ~
    #disable_delivery:     ~
    #logging:              %kernel.debug%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Ace\UserBundle\Entity\User
    service:
       # mailer: fos_user.mailer.default
       mailer: fos_user.mailer.twig_swift
    from_email:
       address:        %email.addr%
       sender_name:    codebender
    registration:
       confirmation:
            enabled: true
            template: AceUserBundle:User:confirmation.email.twig
       form:
            type: ace_user_registration
            handler: ace_user.form.handler.registration
    resetting:
       email:
           template: AceUserBundle:User:resetting.email.twig

doctrine_mongodb:
    connections:
        default:
            server:  %mongo.uri% 
            options:
                connect: true
    default_database: %mongo.dbname%
    document_managers:
        default:
            auto_mapping: true

services:
