AceOwnerBundle:
    resource: "@AceOwnerBundle/Resources/config/routing.yml"
    prefix:   /owner

AceGenericBundle:
    resource: "@AceGenericBundle/Resources/config/routing.yml"
    prefix:   /

AceProjectBundle:
    resource: "@AceProjectBundle/Resources/config/routing.yml"
    prefix:   /project

AceSenderBundle:
    resource: "@AceSenderBundle/Resources/config/routing.yml"
    prefix:   /send

AceBlogBundle:
    resource: "@AceBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

AceUtilitiesBundle:
    resource: "@AceUtilitiesBundle/Resources/config/routing.yml"
    prefix:   /utilities

AceStaticBundle:
    resource: "@AceStaticBundle/Resources/config/routing.yml"
    prefix:   /static

AceSearchBundle:
    resource: "@AceSearchBundle/Resources/config/routing.yml"
    prefix:   /search

AceUserBundle:
    resource: "@AceUserBundle/Resources/config/routing.yml"
    prefix:   /users

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
# temp rss feed fix
rss_feed_fix:
       pattern: /misc/blog/rss
       defaults: { _controller: AceBlogBundle:Default:rss }
