parameters:
#    ace_sender.example.class: Ace\SenderBundle\Example

services:
#    ace_sender.example:
#        class: %ace_sender.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
