parameters:
#    ace_search.example.class: Ace\SearchBundle\Example

services:
#    ace_search.example:
#        class: %ace_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
